-- sample 계정 없으신 분들만!
CREATE USER sample IDENTIFIED BY sample;
GRANT RESOURCE, CONNECT TO sample;
GRANT UNLIMITED TABLESPACE TO sample;


-- sample 계정 접속해서
CREATE TABLE MEMBER(
    NAME VARCHAR(50),
    AGE NUMBER,
    ADDR VARCHAR(100)
);

-- INSERT 구문
INSERT INTO MEMBER(NAME, AGE, ADDR) VALUES('가가가', 1, '나나나');

COMMIT;

SELECT * FROM MEMBER;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(150) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL
);